### PR TITLE
Try build kmod for currente kernel and let it debug 

### PR DESCRIPTION
**Pull request by sergiomb2**
`rfpkg --release f35  mockbuild --no-local-resultsdir -N --root fedora-35-x86_64-rpmfusion_free`
(...)
Build failed 
to debug: 
```
mock -r fedora-35-x86_64-rpmfusion_free --shell
su - mockbuild
cd build/BUILD/hid-ite8291r3-kmod-0.0/_kmod_build_5.18.7-100.fc35.x86_64/
make -j8 KDIR=/usr/src/kernels/5.18.7-100.fc35.x86_64
```

### CODE REVIEW

**Comment by sergiomb2** [comment]
and you can edit makefile outside of buildroot
vi /var/lib/mock/fedora-35-x86_64/root/builddir/build/BUILD/hid-ite8291r3-kmod-0.0/_kmod_build_5.18.7-100.fc35.x86_64/Makefile

**Comment by sergiomb2** [comment]
on makefile you need use tabs , not spaces

**Comment by cowboysmall** [comment]
Thanks so much for the feedback. I caught the spaces / tabs issue (my editor).

**Comment by cowboysmall** [comment]
The build completed and I tried to install:

```
dnf install ./akmod-hid-ite8291r3-0.0-1.fc36.1.x86_64.rpm ./hid-ite8291r3-kmod-0.0-1.fc36.1.x86_64.rpm 
Last metadata expiration check: 0:06:33 ago on Mon 29 Aug 2022 13:39:50.
Error: 
 Problem: conflicting requests
  - nothing provides hid-ite8291r3-kmod-common >= 0.0 needed by akmod-hid-ite8291r3-0.0-1.fc36.1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by sergiomb2** [comment]
`dnf install ./hid-ite8291r3-0.0-1.fc35.1.x86_64.rpm ./akmod-hid-ite8291r3-0.0-1.fc36.1.x86_64.rpm`

hid-ite8291r3-0.0-1.fc35.1.x86_64.rpm provides the hid-ite8291r3-kmod-common

**Comment by cowboysmall** [comment]
I don't have that, or at least the corresponding built for fc36. These are the files I have:

```
ls -la
total 304
drwxrwsr-x. 1 jerry mock    572 Aug 29 14:38 .
drwxrwsr-x. 1 root  mock     48 Aug 29 14:38 ..
-rw-r--r--. 1 jerry mock  23478 Aug 29 14:38 akmod-hid-ite8291r3-0.0-1.fc36.1.x86_64.rpm
-rw-rw-r--. 1 jerry mock  23717 Aug 29 14:38 build.log
-rw-r--r--. 1 jerry mock  21334 Aug 29 14:38 hid-ite8291r3-kmod-0.0-1.fc36.1.src.rpm
-rw-r--r--. 1 jerry mock  15528 Aug 29 14:38 hid-ite8291r3-kmod-0.0-1.fc36.1.x86_64.rpm
-rw-rw-r--. 1 jerry mock   3217 Aug 29 14:37 hw_info.log
-rw-rw-r--. 1 jerry mock  20978 Aug 29 14:38 installed_pkgs.log
-rw-r--r--. 1 jerry mock   6413 Aug 29 14:38 kmod-hid-ite8291r3-0.0-1.fc36.1.x86_64.rpm
-rw-r--r--. 1 jerry mock  13566 Aug 29 14:38 kmod-hid-ite8291r3-5.19.4-200.fc36.x86_64-0.0-1.fc36.1.x86_64.rpm
-rw-rw-r--. 1 jerry mock 160473 Aug 29 14:38 root.log
-rw-rw-r--. 1 jerry mock    883 Aug 29 14:38 state.log
```

As per the recommendation of someone on the mailing list thread, I removed the parts of the spec file that referred to a common package.

J.K.

**Comment by cowboysmall** [comment]
So it seems to have built the kernel module without issue, 

```
> ls -la
total 776
drwxr-xr-x. 1 mockbuild mock    590 Aug 29 15:13 .
drwxr-xr-x. 1 mockbuild mock    286 Aug 29 14:51 ..
-rw-r--r--. 1 mockbuild mock    363 Aug 29 14:51 .Module.symvers.cmd
-rw-r--r--. 1 mockbuild mock    430 Jun  1 13:37 .gitignore
-rw-r--r--. 1 mockbuild mock    481 Aug 29 14:51 .hid-ite8291r3.ko.cmd
-rw-r--r--. 1 mockbuild mock    352 Aug 29 14:51 .hid-ite8291r3.mod.cmd
-rw-r--r--. 1 mockbuild mock  31894 Aug 29 14:51 .hid-ite8291r3.mod.o.cmd
-rw-r--r--. 1 mockbuild mock  44755 Aug 29 14:51 .hid-ite8291r3.o.cmd
-rw-r--r--. 1 mockbuild mock    329 Aug 29 14:51 .modules.order.cmd
-rw-r--r--. 1 mockbuild mock  18092 Jun  1 13:37 LICENSE
-rw-r--r--. 1 mockbuild mock    176 Aug 29 14:51 Makefile
-rw-r--r--. 1 mockbuild mock      0 Aug 29 14:51 Module.symvers
-rw-r--r--. 1 mockbuild mock   3692 Jun  1 13:37 README.md
-rw-r--r--. 1 mockbuild mock    219 Jun  1 13:37 dkms.conf
-rw-r--r--. 1 mockbuild mock  13550 Jun  1 13:37 hid-ite8291r3.c
-rw-r--r--. 1 mockbuild mock 312632 Aug 29 14:51 hid-ite8291r3.ko
-rw-r--r--. 1 mockbuild mock     96 Aug 29 14:51 hid-ite8291r3.mod
-rw-r--r--. 1 mockbuild mock    710 Aug 29 14:51 hid-ite8291r3.mod.c
-rw-r--r--. 1 mockbuild mock  49656 Aug 29 14:51 hid-ite8291r3.mod.o
-rw-r--r--. 1 mockbuild mock 264504 Aug 29 14:51 hid-ite8291r3.o
-rw-r--r--. 1 mockbuild mock     97 Aug 29 14:51 modules.order

```

but it doesn't seem to have installed the kernel module. It has installed the other files - i.e. the udev configuration, etc - am I missing a step?

Thanks again,

J.K.

**Comment by sergiomb2** [comment]
you need rebuild it with the commit  that you reverted

after install the packages, you need run as root `akmods`

**Comment by cowboysmall** [comment]
Done and done. I needed to install the following for the akmods command to succeed:

`dnf install buildsys-build-rpmfusion buildsys-build-rpmfusion-kerneldevpkgs-current`

Do you know why? How is it when I install - for example - the nvidia kmod I don't have to run akmods or install those dependencies? 

So I am going to reboot and test - if all succeeds what next? Should I set up a build on copr? Or should Itry to submit it to RPMFusion? If so, what steps should I take?

Thanks again so much for your time and help.

J.K.

**Comment by cowboysmall** [comment]
Restarted and it works perfectly. Thanks so much for our time and patience.

So what if I want this package to be generally available? As you may know, it's a kernel module for a specific keyboard that allows you to control the RGB backlight (used on Slimbook laptops, Tuxedo laptops, and so on).

What are my next steps? Do I create a build on pagure? Also how do I build it so I don't need to run akmods - or did I need to run akmods because the build failed?

Thanks again,

J.K.

**Comment by sergiomb2** [comment]
> Done and done. I needed to install the following for the akmods command to succeed:
> 
> `dnf install buildsys-build-rpmfusion buildsys-build-rpmfusion-kerneldevpkgs-current`
> 
> Do you know why? How is it when I install - for example - the nvidia kmod I don't have to run akmods or install those dependencies?
> 

yes, correct , seems it is a bug on kmodtool / akmods , I'm investigating that 

> So I am going to reboot and test - if all succeeds what next? Should I set up a build on copr? Or should Itry to submit it to RPMFusion? If so, what steps should I take?
> 

no need to reboot , just run `modprobe hid-ite8291r3`


> Thanks again so much for your time and help.
> 
> J.K.

**Comment by sergiomb2** [comment]
> Restarted and it works perfectly. Thanks so much for our time and patience.
> 
> So what if I want this package to be generally available? As you may know, it's a kernel module for a specific keyboard that allows you to control the RGB backlight (used on Slimbook laptops, Tuxedo laptops, and so on).
> 
> What are my next steps? Do I create a build on pagure? Also how do I build it so I don't need to run akmods - or did I need to run akmods because the build failed?


yes, I think source in pagure and build in copr , is a good step , at least if someone want try it , can test it with your repo

> Thanks again,
> 
> J.K.

**Comment by cowboysmall** [comment]
> > Done and done. I needed to install the following for the akmods command to succeed:
> > `dnf install buildsys-build-rpmfusion buildsys-build-rpmfusion-kerneldevpkgs-current`
> > Do you know why? How is it when I install - for example - the nvidia kmod I don't have to run akmods or install those dependencies?
> 
> yes, correct , seems it is a bug on kmodtool / akmods , I'm investigating that

Thanks for the update - would have likely caused me a headache thinking about it.


 
> > So I am going to reboot and test - if all succeeds what next? Should I set up a build on copr? Or should Itry to submit it to RPMFusion? If so, what steps should I take?
> 
> no need to reboot , just run `modprobe hid-ite8291r3`

I know I could have loaded the module, but I needed to reboot because I wanted to see the backlight come on during boot.

**Comment by cowboysmall** [comment]
> > Done and done. I needed to install the following for the akmods command to succeed:
> > `dnf install buildsys-build-rpmfusion buildsys-build-rpmfusion-kerneldevpkgs-current`
> > Do you know why? How is it when I install - for example - the nvidia kmod I don't have to run akmods or install those dependencies?
> 
> yes, correct , seems it is a bug on kmodtool / akmods , I'm investigating that

So I assume when the bug has been fixed / resolved I will be safely able to uninstall the two packages I needed to install? 

`dnf remove buildsys-build-rpmfusion buildsys-build-rpmfusion-kerneldevpkgs-current`

and also I won't have to manually run akmods?

J.K.

**Comment by cowboysmall** [comment]
Thanks again for your help. I have added [a copr build](https://copr.fedorainfracloud.org/coprs/cowboysmall/hid-ite8291r3-kmod/) and [a repository on pagure](https://pagure.io/hid-ite8291r3-kmod) which mirrors this repository (but has yet to update).

I have tested installation through copr and it seems to work fine. Let me know if you find any issues. And let me know what you think next steps (if any) should be.

Thanks again,

J.K.

**Pull request merged**
